apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # count of pods
  replicas: 3
  selector: 
    # more than 1  pods
    matchLabels:
      app: client
  template:
   #เราจะ deploy อะไร
    metadata:
      name: client-pod
      labels:                   
        app: client
    spec:
      containers:                
        - name: client
          image: dekcode/todo-app:v4

--- 
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: ClusterIP
  selector:
    # from deployment
    app: client
  ports:
    - port: 80
      # ตัวอย่าง: Node.js 3000 หรือ 80 สำหรับ .NET
      targetPort: 80
      # Range: 30000 - 32767
      # nodePort: 30001


