apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  # count of pods
  replicas: 3
  selector: 
    # more than 1  pods
    matchLabels:
      app: server
  template:
   #เราจะ deploy อะไร
    metadata:
      name: server-pod
      labels:                   
        app: server
    spec:
      containers:                
        - name: server
          image: dekcode/todo-api:v5

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: server-service-nodeport
# spec:
#   type: NodePort
#   selector:
#     # from deployment
#     app: server
#   ports:
#     - port: 80
#       # ตัวอย่าง: Node.js 3000 หรือ 80 สำหรับ .NET
#       targetPort: 80
#       # Range: 30000 - 32767
#       nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP
  selector:
    # from deployment
    app: server
  ports:
    - port: 80
      # ตัวอย่าง: Node.js 3000 หรือ 80 สำหรับ .NET
      targetPort: 80




