apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 3000         # Port ที่ service เปิดให้ cluster ภายในเรียก
      targetPort: 3000   # Port ที่ container (pod) ฟังอยู่
      nodePort: 32000    # Port ที่ใช้เข้าจากภายนอกผ่าน IP ของ Node
