apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client  
spec:
  containers:
  - name: client-container
    image: pongphisut/gclient
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: client 
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
